# Generated by Django 2.0 on 2018-04-24 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('kind', models.PositiveIntegerField(choices=[(0, 'simple'), (1, 'multi'), (2, 'priority_list')])),
            ],
        ),
        migrations.CreateModel(
            name='MultiVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multivote', to='votes.Candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multivote', to='votes.Election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multivote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PriorityVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveSmallIntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorityvote', to='votes.Candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorityvote', to='votes.Election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorityvote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SimpleVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simplevote', to='votes.Candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simplevote', to='votes.Election')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simplevote', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='votes.Election'),
        ),
        migrations.AlterUniqueTogether(
            name='simplevote',
            unique_together={('election', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='priorityvote',
            unique_together={('candidate', 'user'), ('election', 'candidate')},
        ),
        migrations.AlterUniqueTogether(
            name='multivote',
            unique_together={('candidate', 'user'), ('election', 'candidate')},
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('election', 'slug')},
        ),
    ]
