# Generated by Django 2.0 on 2018-04-24 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='election',
            name='kind',
            field=models.PositiveIntegerField(choices=[(0, 'Simple'), (1, 'Multi'), (2, 'Priority list')]),
        ),
    ]
