# Generated by Django 2.0.4 on 2018-04-19 20:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=20)),
                ('display_name', models.CharField(max_length=140)),
            ],
        ),
        migrations.RemoveField(
            model_name='value',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='poll',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='user',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='value',
        ),
        migrations.CreateModel(
            name='MultiVote',
            fields=[
                ('basevote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='votes.BaseVote')),
            ],
            bases=('votes.basevote',),
        ),
        migrations.CreateModel(
            name='SimpleVote',
            fields=[
                ('basevote_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='votes.BaseVote')),
            ],
            bases=('votes.basevote',),
        ),
        migrations.RenameModel(
            old_name='Poll',
            new_name='Election',
        ),
        migrations.DeleteModel(
            name='Value',
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
        migrations.AddField(
            model_name='candidate',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='votes.Election'),
        ),
        migrations.AddField(
            model_name='basevote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='votes.Candidate'),
        ),
        migrations.AddField(
            model_name='basevote',
            name='election',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='votes.Election'),
        ),
        migrations.AddField(
            model_name='basevote',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('election', 'slug')},
        ),
    ]
