# Generated by Django 2.0.4 on 2018-05-24 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0002_auto_20180424_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multivote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multivotes', to='votes.Candidate'),
        ),
        migrations.AlterField(
            model_name='priorityvote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priorityvotes', to='votes.Candidate'),
        ),
        migrations.AlterField(
            model_name='simplevote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simplevotes', to='votes.Candidate'),
        ),
    ]
